services:
  # proxy:
  #   image: nginx:latest
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #     # Uncomment the next line if you want HTTPS later
  #     # - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - app
  #   restart: unless-stopped
  app:
    build: .
    ports:
      - "${APP_PORT}:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgresql://${ADMIN_USERNAME}:${ADMIN_PASSWORD}@db:5432/hydra_db
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${ADMIN_USERNAME}
      - POSTGRES_PASSWORD=${ADMIN_PASSWORD}
      - POSTGRES_DB=hydra_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
